// Database implements a scoped slice of Module N
// (docs/02_Functional_Requirements.md): FR-061 (Managed Database
// Provisioning), FR-062 (Isolation Enforcement), FR-065 (Deprovisioning on
// Deletion), and the substance of FR-063 (credentials generated by the
// platform and delivered to the application's runtime, never authored or
// stored by the employee/agent).
//
// Scope adaptations, stated plainly rather than left to be discovered:
//
//   - **FR-063 names Module O (Secret Management) as the delivery
//     mechanism, and Module O does not exist.** Credentials are generated
//     here and injected into the application's runtime as an environment
//     variable, which satisfies the half of FR-063 that protects the
//     employee/agent ("never appear in deployment.yaml, source control, or
//     build logs" — they don't). What is NOT satisfied is at-rest
//     protection: the generated password is stored in the platform's own
//     database in plaintext, because there is no secret store to put it in.
//     That is a real security limitation, not a technicality — anyone with
//     read access to the platform database can read every application's
//     database password. It is the single largest reason Module O should
//     come before this is used for anything real.
//   - **FR-064 (Backup Scheduling) is not implemented.** It needs a
//     scheduler this platform doesn't have and a frequency/retention policy
//     the requirement itself marks TBD; inventing one would be inventing a
//     business decision.
//   - FR-062's detection half ("a cross-application connection attempt is
//     detected and logged as a policy violation") is not implemented — that
//     needs Module Q's network policy layer. The *prevention* half is real:
//     see the package comment on runtimeengine's CreateNetwork.
package domain

import (
	"errors"
	"time"
)

// ContainerSpec is what the Runtime Platform needs to start one
// application container. It became a struct when Module N added
// environment variables and a private network to what had been a
// four-argument call — the shape a Kubernetes-backed implementation would
// need too, per NFR-046.
type ContainerSpec struct {
	Name          string
	ImageRef      string
	ContainerPort int
	// Env entries are "KEY=value", matching Docker's own convention.
	Env []string
	// NetworkID is the application's private network (FR-062). Empty for
	// an application with no database, which then behaves exactly as it
	// did before Module N.
	NetworkID string
}

// DatabaseSpec is what the Runtime Platform needs to start one
// application's dedicated database.
type DatabaseSpec struct {
	Name         string
	ImageRef     string
	NetworkID    string
	DatabaseName string
	Username     string
	Password     string
}

type DatabaseStatus string

const (
	DatabaseProvisioned   DatabaseStatus = "provisioned"
	DatabaseDeprovisioned DatabaseStatus = "deprovisioned"
)

// ProvisionedDatabase is the platform's record of one application's
// managed database. One per application at most — FR-061/FR-062's
// "logically isolated and dedicated to that application".
type ProvisionedDatabase struct {
	ID            string
	ApplicationID string
	Engine        string // "postgres" — the only supported engine today
	ContainerID   string
	NetworkID     string
	// Host is the database container's name, which Docker resolves for
	// any container on the same private network. There is deliberately no
	// host port: the database is unreachable from outside that network.
	Host            string
	Port            int
	DatabaseName    string
	Username        string
	Password        string
	Status          DatabaseStatus
	ProvisionedAt   time.Time
	DeprovisionedAt *time.Time
}

var (
	ErrDatabaseNotProvisioned = errors.New("application has no provisioned database")
	// ErrUnsupportedDatabaseType guards FR-061's exception flow: a
	// declared type outside the supported catalog never reaches
	// provisioning.
	ErrUnsupportedDatabaseType = errors.New("declared database type is not supported")
)
