// Database implements a scoped slice of Module N
// (docs/02_Functional_Requirements.md): FR-061 (Managed Database
// Provisioning), FR-062 (Isolation Enforcement), FR-065 (Deprovisioning on
// Deletion), and the substance of FR-063 (credentials generated by the
// platform and delivered to the application's runtime, never authored or
// stored by the employee/agent).
//
// Scope adaptations, stated plainly rather than left to be discovered:
//
//   - **FR-063's credentials live in Module O (Secret Management).** The
//     generated password is sealed into the secret store as a
//     platform-managed secret (DatabasePasswordSecret) before the database
//     is even started, and decrypted only when a container starts with it.
//     Before Module O existed it was stored in this table in plaintext;
//     DatabaseService.MigrateLegacyPlaintextPasswords moves any such row
//     into the store at startup. What is still NOT solved is the key
//     itself — see internal/secretbox on why an environment variable is
//     not a KMS.
//   - **FR-064 (Backup Scheduling) is not implemented.** It needs a
//     scheduler this platform doesn't have and a frequency/retention policy
//     the requirement itself marks TBD; inventing one would be inventing a
//     business decision.
//   - FR-062's detection half ("a cross-application connection attempt is
//     detected and logged as a policy violation") is not implemented — that
//     needs Module Q's network policy layer. The *prevention* half is real:
//     see the package comment on runtimeengine's CreateNetwork.
package domain

import (
	"errors"
	"time"
)

// ContainerSpec is what the Runtime Platform needs to start one
// application container. It became a struct when Module N added
// environment variables and a private network to what had been a
// four-argument call — the shape a Kubernetes-backed implementation would
// need too, per NFR-046.
type ContainerSpec struct {
	Name          string
	ImageRef      string
	ContainerPort int
	// Env entries are "KEY=value", matching Docker's own convention.
	Env []string
	// NetworkID is the application's private network (FR-062). Empty for
	// an application with no database, which then behaves exactly as it
	// did before Module N.
	NetworkID string
}

// DatabaseSpec is what the Runtime Platform needs to start one
// application's dedicated database.
type DatabaseSpec struct {
	Name         string
	ImageRef     string
	NetworkID    string
	DatabaseName string
	Username     string
	Password     string
}

type DatabaseStatus string

const (
	DatabaseProvisioned   DatabaseStatus = "provisioned"
	DatabaseDeprovisioned DatabaseStatus = "deprovisioned"
)

// ProvisionedDatabase is the platform's record of one application's
// managed database. One per application at most — FR-061/FR-062's
// "logically isolated and dedicated to that application".
type ProvisionedDatabase struct {
	ID            string
	ApplicationID string
	Engine        string // "postgres" — the only supported engine today
	ContainerID   string
	NetworkID     string
	// Host is the database container's name, which Docker resolves for
	// any container on the same private network. There is deliberately no
	// host port: the database is unreachable from outside that network.
	Host            string
	Port            int
	DatabaseName    string
	Username        string
	Status          DatabaseStatus
	ProvisionedAt   time.Time
	DeprovisionedAt *time.Time
}

// LegacyDatabasePassword is a password Module N stored in plaintext before
// Module O existed — read only so it can be moved into the secret store.
type LegacyDatabasePassword struct {
	DatabaseID    string
	ApplicationID string
	Password      string
}

var (
	ErrDatabaseNotProvisioned = errors.New("application has no provisioned database")
	// ErrUnsupportedDatabaseType guards FR-061's exception flow: a
	// declared type outside the supported catalog never reaches
	// provisioning.
	ErrUnsupportedDatabaseType = errors.New("declared database type is not supported")
)
