// Secret implements the core types for Module O (Secret Management) —
// docs/02_Functional_Requirements.md FR-066–071 and
// docs/11_Security_Requirements.md Section 5.
//
// Scope, stated plainly rather than left to be discovered:
//
//   - FR-066, FR-067, FR-069 and FR-070 are implemented: values are
//     encrypted at rest (internal/secretbox), scoped to one application,
//     injected into every container start, and never returned by anything
//     once submitted.
//   - Values are submitted by a human through the Platform API, never
//     through the MCP server. SEC-SECRET-3 says "the AI agent's role is
//     limited to declaring that a secret is needed ... never to handling,
//     viewing, or relaying the value". That is stricter than FR-066's
//     "Employee/Agent submits a secret value", so it wins.
//   - deployment.yaml does not reference secrets by name. FR-023's contract
//     is exactly six top-level keys and none of them is `secrets`; adding
//     one is a contract change, not an implementation detail. Instead,
//     every secret registered to an application is injected into every one
//     of its containers, as an environment variable of the same name.
//   - FR-068 (rotation) is not implemented as specified. Replacing a value
//     works and takes effect at the next container start (a Restart applies
//     it at once), but there is no overlap window, no scheduled rotation,
//     and nothing invalidates the old value — which, for a third-party API
//     key, only the third party can do anyway.
//   - FR-071 (approval for production secret operations) is not
//     implemented; it needs the approval workflow and RBAC that don't exist.
package domain

import (
	"errors"
	"regexp"
	"strings"
	"time"
)

type SecretManagedBy string

const (
	// SecretManagedByEmployee: registered by an application owner through
	// the API. Any active owner can list, replace or delete it.
	SecretManagedByEmployee SecretManagedBy = "employee"
	// SecretManagedByPlatform: generated by the platform itself — today only
	// Module N's database password. Visible by name, never changeable or
	// deletable directly, because something else depends on it.
	SecretManagedByPlatform SecretManagedBy = "platform"
)

// DatabasePasswordSecret is where Module N keeps the password it generates
// for an application's database (FR-063).
const DatabasePasswordSecret = "DATABASE_PASSWORD"

// MaxSecretValueBytes bounds a value to something that is plausibly a
// credential and comfortably fits in a process environment.
const MaxSecretValueBytes = 8192

// ApplicationSecret is one stored secret. There is deliberately no
// plaintext field: the value exists in memory only while being sealed, or
// while being handed to a container that is about to start.
type ApplicationSecret struct {
	ID            string
	ApplicationID string
	Name          string
	ManagedBy     SecretManagedBy
	Ciphertext    []byte
	KeyID         string
	Version       int
	CreatedBy     *string
	UpdatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// SecretMetadata is everything about a secret that may leave the platform:
// its name and its history, never its value (FR-070).
type SecretMetadata struct {
	Name      string
	ManagedBy SecretManagedBy
	Version   int
	UpdatedBy *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (s ApplicationSecret) Metadata() SecretMetadata {
	return SecretMetadata{
		Name: s.Name, ManagedBy: s.ManagedBy, Version: s.Version,
		UpdatedBy: s.UpdatedBy, CreatedAt: s.CreatedAt, UpdatedAt: s.UpdatedAt,
	}
}

var secretNamePattern = regexp.MustCompile(`^[A-Z][A-Z0-9_]{0,63}$`)

// reservedSecretPrefixes are the environment-variable names the platform
// injects itself. Without this, a secret named DATABASE_URL would silently
// replace the connection string Module N hands the application.
var reservedSecretPrefixes = []string{"DATABASE_", "PLATFORM_"}

// ValidateSecretName enforces that a secret's name is usable as the
// environment variable it will be injected as.
func ValidateSecretName(name string) error {
	if !secretNamePattern.MatchString(name) {
		return ErrInvalidSecretName
	}
	for _, prefix := range reservedSecretPrefixes {
		if strings.HasPrefix(name, prefix) {
			return ErrReservedSecretName
		}
	}
	return nil
}

func ValidateSecretValue(value string) error {
	if value == "" || len(value) > MaxSecretValueBytes || strings.ContainsRune(value, 0) {
		return ErrInvalidSecretValue
	}
	return nil
}

var (
	ErrInvalidSecretName       = errors.New("secret name must look like an environment variable: uppercase letters, digits and underscores, starting with a letter, at most 64 characters")
	ErrReservedSecretName      = errors.New("secret names starting with DATABASE_ or PLATFORM_ are reserved for values the platform injects itself")
	ErrInvalidSecretValue      = errors.New("secret value must be non-empty, at most 8192 bytes, and contain no NUL bytes")
	ErrSecretNotFound          = errors.New("secret not found")
	ErrSecretManagedByPlatform = errors.New("this secret is managed by the platform and cannot be changed or removed directly")
	// ErrSecretUnreadable is FR-067's exception flow: a container whose
	// secret cannot be decrypted does not start without it.
	ErrSecretUnreadable = errors.New("a stored secret could not be decrypted")
)
